const allMemories = [
    {textrus: '... наш поцелуй в каньоне в пустыне Египта.',
    texteng: '...our kiss in canyon in Egypt desert.' },
    {textrus: '... лицо того мужика из Минска.',
    texteng: '...that guys face in Minsk.' },
    {textrus: '... как нельзя было нырнуть в Мертвом море.',
    texteng: '...how we cant dive in Dead sea in Israel.' },
    {textrus: '...как мы покорили Московский марафон.',
    texteng: '...conquered the Moscow Marathon.' },
    {textrus: '...вкусный плов из Узбекистана.',
    texteng: '...delicious pilaf from Uzbekistan.' },
    {textrus: '...теплую водичку Памуккале.',
    texteng: '...warm Pamukkale water.' },
    {textrus: '...что вы моя пушинка.',
    texteng: '...that you are my fluff.' },
    {textrus: '...что везде можно найти тепло.',
    texteng: '...that you can find warmth everywhere.' },
    {textrus: '...закаты в Мармарисе.',
    texteng: '...sunsets in Marmaris.' },
    {textrus: '...мое любимое ваше место.',
    texteng: '...my favorite place of yours.' },
    {textrus: '...наш полет на воздушном шаре.',
    texteng: '...our balloon flight.' },
    {textrus: '...наши прогулки по пустыням Каппадокии.',
    texteng: '...our walks through the deserts of Cappadocia.' },
    {textrus: '...что вы моя половинка.',
    texteng: '...that you are my soul mate.' },
    {textrus: '...как мы побывали в самом высоком здании.',
    texteng: '...how we visited the tallest building.' },
    {textrus: '...покорение гор в Гудаури.',
    texteng: '...conquering the mountains in Gudauri.' },
    {textrus: '...как мы побывали в прошлом.',
    texteng: '...how we have been in the past.' },
    {textrus: '...наш 2017 Новый год.',
    texteng: '...our 2017 new year.' },
    {textrus: '...катание на коньках в сказке.',
    texteng: '...ice skating in a fairy tale.' },
    {textrus: '...как мы кушали яичницу с лопаты.',
    texteng: '...how we ate scrambled eggs made with a shovel.' },
    {textrus: '...наши прогулки по Риге.',
    texteng: '...our walks in Riga.' },
    {textrus: '...как мы катались на слонике.',
    texteng: '...how we rode an elephant.' },
    {textrus: '...что вы не останетесь голодной в тундре.',
    texteng: '...that you wont stay hungry in the tundra.' },
    {textrus: '...козла, который почти скушал букет.',
    texteng: '...the goat who almost ate the bouquet.' },
    {textrus: '...как мы летали на самолетике.',
    texteng: '...how we flew on an airplane.' },
    {textrus: '...что я готов всегда носить вас на ручках.',
    texteng: '...that I am always ready to carry you on my hands.' },
    {textrus: '...что вы моя Вселенная.',
    texteng: '...that you are my universe.' },
    {textrus: '...наши прогулки по разным берегам.',
    texteng: '...our walks on different shores.' },
    {textrus: '...что наша любовь гарантирована навеки.',
    texteng: '...that our love is guaranteed forever' },
    {textrus: '...наше паромное путешествие.',
    exteng: '...our ferry trip.' },
    {textrus: '...кристальный лед в горах Алматы.',
    texteng: '...crystal ice in the mountains of Almaty.' },
    {textrus: '...наш обед в ресторане Мишлен.',
    texteng: '...our lunch at the Michelin restaurant.' },
    {textrus: '...наше путешествие в Будущее.',
    texteng: '...our journey into the future.' },
    {textrus: '...что мы с вами за ЗОЖ.',
    texteng: '...that we are stand for a healthy lifestyle.'},
    {textrus: '...вкусный баурсак.',
    texteng: '...delicious baursak.'},
    {textrus: '...день, когда мы взяли Шпулю.',
    texteng: '...the day we took Shpoolya.' },
    {textrus: '...что у нас очень прямые руки.',
    texteng: '...that we have very straight hands.' },
    {textrus: '...наши профессиональные дайверские заплывы.',
    texteng: '...our professional diving swims.' },
    {textrus: '...как мы нашли пухлого ежика.',
    texteng: '...how we found a chubby hedgehog.' },
    {textrus: '...что мы с вами умняши.',
    texteng: '...that we are smart.' },
    {textrus: '...что мы заядлые сноубордисты.',
    texteng: '...that we are avid snowboarders.' },
    {textrus: '...нашу конную прогулку.',
    texteng: '...our horse ride.'},
    {textrus: '...как мы покорили гору в поисках козлят.',
    texteng: '...how we conquered the mountain in search of goats.'},
    {textrus: '...наш трип через всю Армению.',
    texteng: '...our trip across Armenia.'},
    {textrus: '...как мы были близко к месту Ледового побоища.',
    texteng: '...how close we were to the site of the Ice Battle.'},
    {textrus: '...наш фейс-арт.',
    texteng: '...our face art.'},
    {textrus: '...что бабачки любят нас.',
    texteng: '...that dogs love us.'},
    {textrus: '...наш свадебный танец.',
    texteng: '...our wedding dance.'},
    {textrus: '...как мы забирали Шкусю.',
    texteng: '...how we took the Shkoosya.'},
    {textrus: '...наши художества.',
    texteng: '...our arts.'},
    {textrus: '...как мы кушали на высоте 50 метров.',
    texteng: '...how we ate at an altitude of 50 meters.'},
    {textrus: '...наши лесные походы.',
    texteng: '...our forest hikes.'},
    {textrus: '...наши походы с палаткой.',
    texteng: '...our camping trips.'},
    {textrus: '...ночные посиделки у костра.',
    texteng: '...night gatherings by the campfire.'},
    {textrus: '...прогулки на сап-серфе по Неве.',
    texteng: '...sap surf walks on the Neva River.'},
    {textrus: '...как мы катались на велосипедах.',
    texteng: '...how we rode bicycles.'},
    {textrus: '...наши сладкие семейные фото.',
    texteng: '...our sweet family photos.'},
    {textrus: '...что Вы - сладкий пирожочек.',
    texteng: '...that you are a sweet pie.'},
    {textrus: '...нашу поездку на ретро-паровозе.',
    texteng: '...our trip on a retro steam locomotive.'},
    {textrus: '...как мы любим уехать от всех.',
    texteng: '...how we love to get away from everyone.'},
    {textrus: '...наши традиционные фото у Елки в Москве.',
    texteng: '...our traditional photos at the Christmas Tree in Moscow.'},
    {textrus: '...путешествия на поезде.',
    texteng: '...traveling by train.'},
    {textrus: '...что даже в снежном лесу нам тепло.',
    texteng: '...that even in the snowy forest we feel warm.'},
    {textrus: '...что вы великолепная фигуристка.',
    texteng: '...that youre a great figure skater.'},   
    {textrus: '...что у моих булочек день рождения в один день.',
    texteng: '...that my buns have a birthday on the same day.'}, 
    {textrus: '...как мы плавали в бассейне зимой.',
    texteng: '...how we swam in the pool in winter.'},
    {textrus: '...что нет ничего слаще Вас.',
    texteng: '...that there is nothing sweeter than you.'},  
    {textrus: '...что вы готовы к переезду на Бали.',
    texteng: '...that you are ready to move to Bali.'},
    {textrus: '...как мы лазили по горам.',
    texteng: '...how we climbed the mountains.'},
    {textrus: '...сладенький нос.',
    texteng: '...sweet nose.'},
    {textrus: '...как мы купались с Барбосей.',
    texteng: '...how we swam with Barbosya.'},
    {textrus: '...наше тюлененье на озерах.',
    texteng: '...our sealing on the lakes.'},
    {textrus: '...как мы нянчили двух девочек.',
    texteng: '...how we pet two girls.'},    
    {textrus: '...как мы не перевернулись.',
    texteng: '...how did we not roll over.'},
    {textrus: '...наш первый беговой финиш.',
    texteng: '...our first running finish.'},
    {textrus: '...что вы в моем сердечке.',
    texteng: '...that you are in my heart.'},
    {textrus: '...что нам с вами не сидится на месте.',
    texteng: '...that you and I are not sitting still.'},
    {textrus: '...мой самый счастливый день.',
    texteng: '...my happiest day.'},
    {textrus: '...день, когда вы стали mrs. Slatvitskaya.',
    texteng: '...the day you became mrs. Slatvitskaya.'},
    {textrus: '...наши вечера на море.',
    texteng: '...our evenings at the sea.'},
    {textrus: '...что мы с вами пуси.',
    texteng: '...that we are sweetcakes.'},
    {textrus: '...нашу поездку 16-часовую на автобусе.',
    texteng: '...our 16-hour bus ride.'},
    {textrus: '...наш сплав.',
    texteng: '...our rafting.'},
    {textrus: '...мой выигрыш в шахматы.',
    texteng: '...my chess winnings.'},  
    {textrus: '...наши культурные вечера.',
    texteng: '...our cultural evenings.'},
    {textrus: '...наши новогодние традиции.',
    texteng: '...our New Year traditions.'},
    {textrus: '...как я убегал от вас (вспотел).',
    texteng: '...how I ran away from you (sweated).'},
    {textrus: '...день, когда я сделал Вам предложение.',
    texteng: '...the day I proposed to you.'},
    {textrus: '...как мы были в Челябинске.',
    texteng: '...how we were in Chelyabinsk together.'},
    {textrus: '...как мы сковали наши колечки.',
    texteng: '...how we forged our rings.'},
    {textrus: '...самый лучший плакатик.',
    texteng: '...the best poster.'},
    {textrus: '...наши спонтанные поездки.',
    texteng: '...our spontaneous trips.'},
    {textrus: '...что лето у нас там, где мы захотим.',
    texteng: '...that summer is where we want it to be.'},
    {textrus: '...вечер с котом и утками около маяка.',
    texteng: '...evening with a cat and ducks near the lighthouse.'},  
    {textrus: '...верблюдов-милашек.',
    texteng: '...camels-cuties.'},
    {textrus: '...как я сделал предложение солнышком.',
    texteng: '...how I proposed to you with sun.'},
    {textrus: '...что вы - мое Счастье.',
    texteng: '...that you are my happiness.'},
    {textrus: '...наши гастро-спорто-путешествия.',
    texteng: '...our gastro-sports trips.'},
    {textrus: '...наш первый полумарафон.',
    texteng: '...our first half marathon.'},
    {textrus: '...что мы побывали за северным полюсом.',
    texteng: '...that we have been beyond the north pole.'},
]